version: '3'

services:
  app:
    build:
      context: app
    ports:
      - "5000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
  
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
    - "80:80"